.github/workflows/gradle-build.yml
configurations/unit-test-configuration/locations/location-1/location-1.json
configurations/unit-test-configuration/locations/location-1/objects/object-1.json
configurations/unit-test-configuration/locations/location-2/location-2.json
configurations/unit-test-configuration/locations/location-2/objects/object-1.json
configurations/unit-test-configuration/locations/location-2/objects/object-3.json
configurations/unit-test-configuration/root.json
configurations/unit-test-configurations/test-config-1-full/locations/location-1/location-1.json
configurations/unit-test-configurations/test-config-1-full/locations/location-1/objects/object-1.json
configurations/unit-test-configurations/test-config-1-full/locations/location-1/objects/object-2.json
configurations/unit-test-configurations/test-config-1-full/locations/location-2/location-2.json
configurations/unit-test-configurations/test-config-1-full/locations/location-2/objects/object-1.json
configurations/unit-test-configurations/test-config-1-full/locations/location-2/objects/object-3.json
configurations/unit-test-configurations/test-config-1-full/root.json
src/main/java/io/rpg/config/ConfigLoader.java
src/test/java/io/rpg/config/ConfigLoaderTest.java

I fixed unit tests for ConfigLoader. Will add some more.
* I thought I fixed it, because it had worked for me, but it keeps failing on CI 🤷🏼‍♂️

fix: unit tests for ConfigLoader

---

configurations/demo-config-1/locations/location-1/location-1.json
configurations/demo-config-1/locations/location-2/location-2.json
src/main/java/io/rpg/Initializer.java
src/main/java/io/rpg/config/model/LocationConfig.java
src/main/java/io/rpg/model/location/LocationModel.java
src/test/java/io/rpg/model/location/LocationModelTest.java

@co012/add bounds to config

---

src/main/java/io/rpg/controller/Controller.java
src/main/java/io/rpg/model/actions/ShowDescriptionAction.java

I used the already implemented TextImagePopup to display the description of an object if it has one.

feat: display object description

---

src/main/java/io/rpg/controller/Controller.java
src/main/java/io/rpg/model/actions/BattleAction.java
src/main/java/io/rpg/model/object/GameObject.java
src/main/java/io/rpg/model/object/Player.java
src/main/java/io/rpg/util/BattleResult.java
src/test/java/io/rpg/battle/BattleTest.java

@ksiek127/rpg 110 battle action

---

src/main/java/io/rpg/config/model/ActionConfigBundle.java

Implemented methods for action config validation introduced as stubs in #27.

feat: add action validation methods

---

src/main/java/io/rpg/controller/Controller.java
src/main/java/io/rpg/model/object/GameObject.java
src/main/java/io/rpg/util/GameObjectFactory.java

After clicking a GameObject with action = null, cosumeAction would throw NullPointerException

fix: null action

---

src/main/java/io/rpg/controller/Controller.java
src/main/java/io/rpg/model/location/LocationModel.java
src/main/java/io/rpg/util/GameObjectFactory.java

@mhawryluk/rpg 121 popup while moving bug fix

---

configurations/demo-config-1/locations/location-1/location-1.json
configurations/demo-config-1/locations/location-2/location-2.json
configurations/demo-config-1/locations/location-3/location-3.json
src/main/java/io/rpg/Initializer.java
src/main/java/io/rpg/config/model/LocationConfig.java
src/main/java/io/rpg/model/location/LocationModel.java

feat: reading adjacent locations for teleportation from config

---

docs/configuration.md

Added battle action to docs. It does not require any props so its description is oneliner.
Should be merged after #76 is merged or closed.

docs: RPG-124 docs for action: `battle`

---

src/main/java/io/rpg/wrapper/WrapperController.java

fix: Fix initializing game from files read in the game

---

build.gradle

feat: deployment

---

configurations/demo-config-2/locations/location-1/objects/chest-1.json

Just a quick fix, see the changes.

fix: demo-config-2: condition for after action for location-1 chest

---

src/main/java/io/rpg/model/actions/condition/ConditionEngine.java

This is now possible as leveling system got implemented

feat: enable level-required condition

---

build.gradle
configurations/demo-config-2/locations/location-1/objects/chest-1.json
configurations/demo-config-2/locations/location-1/objects/samurai-1.json
configurations/demo-config-2/locations/location-2/objects/bandit-1.json
configurations/demo-config-2/locations/location-3/objects/bandit-1.json
configurations/demo-config-2/locations/location-3/objects/bandit-2.json
configurations/demo-config-2/locations/location-5/objects/bandit-1.json
configurations/demo-config-2/locations/location-5/objects/bandit-2.json
configurations/demo-config-2/root.json

@kkafar/quick fixes 2

---

src/main/java/io/rpg/model/actions/ActionEngine.java
src/main/java/io/rpg/model/object/Player.java
src/main/java/io/rpg/util/ActionFactory.java
src/main/java/io/rpg/view/popups/QuestionPopup.java

fix: remove merging artifacts

---

configurations/demo-config-2/locations/location-0/objects/key-1.json
src/main/java/io/rpg/controller/Controller.java
src/main/java/io/rpg/model/actions/Action.java
src/main/java/io/rpg/model/actions/BaseActionEmitter.java
src/main/java/io/rpg/util/ActionFactory.java
src/test/java/io/rpg/model/location/LocationModelTest.java

Action can be defined recursively now (see new key configuration) - and it works!

feat: allow for action tree composition

---

docs/configuration.md
src/main/java/io/rpg/config/model/ConditionConfigBundle.java
src/main/java/io/rpg/model/actions/ConditionType.java
src/main/java/io/rpg/model/actions/condition/ConditionEngine.java
src/main/java/io/rpg/model/actions/condition/ConditionFactory.java
src/main/java/io/rpg/model/actions/condition/PointsRequiredCondition.java

Added `points-required` action condition. You can test it on slightly modified demo.

feat: add `points-required` action condition

---

docs/configuration.md

Updated `assetPath` prop description & added some examples

docs: update `assetPath` prop description & add examples

---

configurations/demo-config-2/locations/location-2/objects/bandit-1.json
configurations/demo-config-2/locations/location-2/objects/bandit-2.json
src/main/java/io/rpg/config/model/ActionConfigBundle.java
src/main/java/io/rpg/model/actions/ActionEngine.java
src/main/java/io/rpg/model/actions/BattleAction.java
src/main/java/io/rpg/model/actions/BattleReflexAction.java
src/main/java/io/rpg/util/ActionFactory.java

You can now configure strength points required to win the battle.
I placed this option in action configuration (`ActionConfigBundle`) not in object (`GameObjectConfig`). However I can see why thats wrong ;D

feat: add possibility to set required strength for battle action

---

configurations/demo-config-2/locations/location-0/objects/key-1.json
configurations/demo-config-2/locations/location-1/objects/chest-1.json
configurations/demo-config-2/locations/location-1/objects/samurai-1.json
configurations/demo-config-2/locations/location-2/objects/bandit-2.json
configurations/demo-config-2/locations/location-2/objects/blocking-bunny.json
configurations/demo-config-2/locations/location-3/objects/bandit-1.json
configurations/demo-config-2/locations/location-3/objects/bandit-2.json
configurations/demo-config-2/locations/location-4/objects/boxer.json
configurations/demo-config-2/locations/location-4/objects/tp-to-the-chick.json
configurations/demo-config-2/locations/location-5/objects/bandit-1.json
configurations/demo-config-2/locations/location-5/objects/bandit-2.json
src/main/java/io/rpg/controller/Controller.java
src/main/java/io/rpg/controller/PopupController.java
src/main/java/io/rpg/model/actions/ActionEngine.java
src/main/java/io/rpg/util/BattleResult.java
src/main/java/io/rpg/view/popups/QuestionPopup.java
src/test/java/io/rpg/battle/BattleTest.java

* Refactor PopupController
* Stop player before opening popups
* Change popup texts to Polish
* Fix grammatical errors

fix: Stop player before popup opens
